baseURL = 'http://lovecore.github.io'
languageCode = 'en-us'
title = 'Rootflag.io'
theme = "blist"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false
noTimes = true

[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Nick"
      introSubtitle = "I'm a Father, hacker and gamer. Welcome to my blog."
      introPhoto = "/picture.jpg"
      logo = "/blist-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/emoji-support/"
        weight = 4

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "lol copyright"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I hack things and tweet about things..."
  twitter = "https://twitter.com/lovecore_FGC"
  linkedin = "https://www.linkedin.com/in/nicholas-c-962265153/"
  github = "https://github.com/Lovecore/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
